platform:ios,'8.4'
pod 'KDCycleBannerView','~>1.1.1'
pod 'AFNetworking', '~> 2.5.0'
pod 'SDWebImage', '~> 3.7.1'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'DZNEmptyDataSet', '~> 1.5'
pod 'MagicalRecord', '~> 2.2'
pod 'PKRevealController', '~> 2.0.6'
pod 'FMDB', '~> 2.5'
pod 'ActionSheetPicker-3.0'
pod 'Masonry'
pod 'SKTagView', '~> 0.2'
